# Generated by Django 4.2 on 2024-01-04 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="is_activ",
            new_name="is_active",
        ),
    ]
